// File generated by FlutterFire CLI.
// ⚠️ DO NOT use this file as-is — it is a placeholder.
//
// Generate the real version by running, from your project root:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command will:
//   1. Ask you to select (or create) a Firebase project
//   2. Register Android/iOS/Web apps automatically
//   3. Overwrite this exact file with your real API keys & App IDs
//   4. Also drop google-services.json (Android) and
//      GoogleService-Info.plist (iOS) into the right folders
//
// Never hand-edit the generated values — always regenerate via the CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to add web support.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_YOUR_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'satpara-naturals-app',
    storageBucket: 'satpara-naturals-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'satpara-naturals-app',
    storageBucket: 'satpara-naturals-app.appspot.com',
    iosBundleId: 'com.satparanaturals.app',
  );
}
